#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=0.2.09
PACKAGE=oases
TOOL=oases
DIRECTORY=/home/ssanders/Documents/de-novo-transcriptome-assembly-pipeline/Project_v5/software/Velvet
STORAGE=/home/ssanders

OPTIONS=$OPTIONS" -B $STORAGE"

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
