#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=0.2.09
PACKAGE=oases
TOOL=oases
DIRECTORY=PWDHERE/software/Velvet
STORAGE=/N/slate,/N/project,/N/u

OPTIONS=$OPTIONS" -B $STORAGE"

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
