#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=1.2.10
PACKAGE=velvet
TOOL=velvetg
DIRECTORY=$PWDHERE/software/Velvet
STORAGE=/home/ssanders

OPTIONS=$OPTIONS" -B $STORAGE"

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
