#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=3.1b
PACKAGE=hmmer
TOOL=hmmpress
DIRECTORY=/home/ssanders/Documents/de-novo-transcriptome-assembly-pipeline/Project_v5/software/Hmmer
STORAGE=/home/ssanders


OPTIONS=$OPTIONS" -B $STORAGE"

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
