#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=3.1b
PACKAGE=hmmer
TOOL=hmmpress
DIRECTORY=PWDHERE/software/Hmmer
STORAGE=/N/home,/N/slate,/N/project


OPTIONS=$OPTIONS" -B $STORAGE"

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
