#!/bin/bash

source ../../setup_files/path_set

if [ ! $(command -v singularity) ]; then
        module load singularity
fi

VERSION=2.11.0
PACKAGE=blast
TOOL=makeblastdb
DIRECTORY=$PWDHERE/software/Blast
STORAGE=/home/ssanders

OPTIONS=$OPTIONS" -B $STORAGE"

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
