#!/bin/bash

if [ ! $(command -v singularity) ]; then
        module load singularity
fi

VERSION=3.2.1
PACKAGE=trinotate
TOOL=Trinotate
DIRECTORY=PWDHERE/software/Trinotate
STORAGE=/N/slate,/N/home,/N/project

OPTIONS=$OPTIONS" -B $STORAGE"

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
