#!/bin/bash

source ../../setup_files/path_set

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=4.1g
PACKAGE=signalp
TOOL=signalp
DIRECTORY=$PWDHERE/software/SignalP
STORAGE=/home/ssanders

OPTIONS=$OPTIONS" -B $STORAGE"

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
