#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=4.1g
PACKAGE=signalp
TOOL=signalp
DIRECTORY=/home/ssanders/Documents/de-novo-transcriptome-assembly-pipeline/Project_v5/software/SignalP
STORAGE=/home/ssanders

OPTIONS=$OPTIONS" -B $STORAGE"

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
