#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=1.04
PACKAGE=soapdenovotrans
TOOL=SOAPdenovo-Trans-127mer
DIRECTORY=$PWDHERE/software/SOAPdenovo
STORAGE=/home/ssanders

OPTIONS=$OPTIONS" -B $STORAGE"

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
